### PR TITLE
added the regex and error message

### LINKED ISSUE #76: Validate the slug field in link and collection
This string will be part of an url, so it should only contain letters from the English alphabet, hyphens (-) and maybe numbers. This is probably easiest to achieve with a regex, and I assume class-validator has a decorator for validating regexes. But feel free to investigate other solutions

### PR DESCRIPTION
**Pull request by FearsomeRover**

### CODE REVIEW

**Review by Dkrisztan — COMMENTED** [review]
Looks good to me, there's a typo though, an 'r' is missing from the word lowercase.

**Comment by FearsomeRover** [comment]
good spot, there is one indeed.

**Review by Tschonti — CHANGES_REQUESTED** [review]
perfect 👌
please add the same decorator to the `slug` property of `CollectionEntity` while were here

**Comment by FearsomeRover** [comment]
Added it.
The collection prisma schema is missing the name field, so i wasn't able to fully test it. Should we fix that, or let them figure it out?

**Comment by Tschonti** [comment]
You can fix it, I'm sure they were going to as well

**Review by Tschonti — APPROVED** [review]
🍾

**Pull request merged**
