### PR TITLE
Feature/52 get trending links

### LINKED ISSUE #51: Track link visits
Create a new model in the DB schema that will represent a visit to one of the links. It should contain only a `linkId` and a timestamp. 
Create an endpoint (`GET /links/{slug}`) that finds the link with that slug in the DB, inserts a new record to the new table with the current timestamp, and then redirects to the link.

[Shorz](https://github.com/kir-dev/shorz) can be of help, the same redirect logic is used there.

### LINKED ISSUE #52: Get trending links
Create an endpoint that returns the X most visited links in the past Y days. (I think X and Y can be hardcoded constants, but they could be query parameters as well).
Depends on #51, probably needs an aggregate query on the newly created table.

### PR DESCRIPTION
**Pull request by Dkrisztan**
Closes #52

### CODE REVIEW

**Comment by Dkrisztan** [comment]
The endpoint returns the top 5 links in the past 7 days with the most visits. It returns a sorted descending array with the `id` and the number of `visits` of each top 5 links.

**Comment by Dkrisztan** [comment]
Changed the code as @Tschonti requested, quite sure it works fine now (returns the whole link with it's visitations). Updated to Prisma 5 which made me change a line in the `main.ts` file.

**Comment by Dkrisztan** [comment]
For some reason eslint and prettier checks are failed probably due to Prisma updates, please look into it @Tschonti

**Comment by Tschonti** [comment]
It looks like the current version of the nest-prisma package depends on prisma v4.x., so that needs to be updated as well. 
https://github.com/notiz-dev/nestjs-prisma/releases/tag/v0.22.0

**Review by Tschonti — CHANGES_REQUESTED** [review]
Also, please add a DTO for the return type of the trending endpoint (it can extend LinkEntity)

**Review by Tschonti — APPROVED** [review]
Well done! 🎉

**Pull request merged**
