### PR TITLE
Authentication & authorization setup

### LINKED ISSUE #18: Authentication + Authorization
- Login with authsch
- Create decorator to use with endpoints

### LINKED ISSUE #93: Endpoint to change role of a user
Add a new endpoint to the user controller:

- PATCH /users/:id/role
- request body should contain only one field, a `UserRole` enum
- should only be available to admin users
- should update the role of the user specified by `id`

### PR DESCRIPTION
**Pull request by Tschonti**
also applied authorization to the submission service & controller
added AuthSch setup to readme
Closes #18

### CODE REVIEW

**Comment by Dkrisztan** [comment]
This commit should close #93 (I had to use this pr and branch as the master branch did not have a user model)

**Comment by Tschonti** [comment]
Ohh sorry, this branch should've been merged long ago

**Review by Dkrisztan — APPROVED** [review]

**Review by Tschonti — COMMENTED** [review]
User dtos are not needed, since the user will never be created/updated from a request from the frontend. Validation is also not needed, user entity can only be created by the auth.service, and class-validator validation won't run for that. So the whole user.entity class is unneccessary, the prisma type will do. 

If you want to pass data in the HTTP body, the @Body decorator has to be put on an object, not a string/enum. So create a changeUserRoleDTO or whatever, with just one field for the role. The enum can be validated with class-validator

If you specify the return type of the controller method, the endpoint will show up in swagger and you can try it out.

Please fix these things. If you don't have time for it in the next few days, no worries, but merge this branch and fix these on a separate branch so the others can work as well.

**Comment by Dkrisztan** [comment]
I applied the changes please take a look at it. If it's alright i'll merge it.

**Comment by Tschonti** [comment]
Good job, thank you!

**Pull request merged**
